### ISSUE TITLE
Throwing error 

### ISSUE THREAD

**Issue by Gauravprakash** [pablichjenkov/component-toolkit#228]
when write this script in common main implementation("io.github.pablichjenkov:component-toolkit:0.5.1")

:shared:iosX64Test: Could not resolve io.github.pablichjenkov:component-toolkit:0.5.1.
Required by:
    project :shared

Possible solution:

**Comment by pablichjenkov** [comment]
The target x64 for iOS is not supported to gain speed in compilation times. I always run some tasks before making a PR and I found that target takes some time. There aren't many iPhones with Intel chip out there if any, that's why I took that decision.
If you are planning to use/contribute to the library I can add the x64 target.
PR welcome 🙂 too

**Comment by pablichjenkov** [comment]
Issue should be fixed in version `0.5.4`
implementation("io.github.pablichjenkov:component-toolkit:0.5.4")
